// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX48zIAN2LDFlp5fcXFp3NkIqqt-rbZgY',
    appId: '1:562429955432:web:0c19ca940af07370939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    authDomain: 'shabakacourse.firebaseapp.com',
    storageBucket: 'shabakacourse.firebasestorage.app',
    measurementId: 'G-M6CVTJTX9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCveKWpXJe_WQHxQjv_034XorEVlm0ZrE4',
    appId: '1:562429955432:android:79a70b76bbae5661939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    storageBucket: 'shabakacourse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXF8BZn--ayzw0hxOd1S8WL4xzlr1ctVU',
    appId: '1:562429955432:ios:28e87b723ca16ec8939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    storageBucket: 'shabakacourse.firebasestorage.app',
    iosClientId: '562429955432-gjifkg9g2q2hnulcso9ibrarr0fqkj6c.apps.googleusercontent.com',
    iosBundleId: 'shabakahub.example.shabakahub2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXF8BZn--ayzw0hxOd1S8WL4xzlr1ctVU',
    appId: '1:562429955432:ios:28e87b723ca16ec8939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    storageBucket: 'shabakacourse.firebasestorage.app',
    iosClientId: '562429955432-gjifkg9g2q2hnulcso9ibrarr0fqkj6c.apps.googleusercontent.com',
    iosBundleId: 'shabakahub.example.shabakahub2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX48zIAN2LDFlp5fcXFp3NkIqqt-rbZgY',
    appId: '1:562429955432:web:c1a0a067ba8b0a8e939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    authDomain: 'shabakacourse.firebaseapp.com',
    storageBucket: 'shabakacourse.firebasestorage.app',
    measurementId: 'G-XW0ZZ0ZV8M',
  );
}
